#!/usr/bin/env python

import sys
import os
import ConfigParser

SHAREFILE="/home/federico/.debug-shares"

def list_shares ():
    os.system ("cat %s" % (SHAREFILE))

def add_share (sharename, path, comment, acl):
    parser = ConfigParser.ConfigParser ()
    if len (parser.read (SHAREFILE)) == 0:
        sys.exit (1)

    if parser.has_section (sharename):
        sys.exit (1)

    parser.add_section (sharename)
    parser.set (sharename, "path", path)
    parser.set (sharename, "comment", comment)
    parser.set (sharename, "usershare_acl", acl)

    file = open (SHAREFILE, "w")
    parser.write (file)
    file.close ()
    
def delete_share (sharename):
    parser = ConfigParser.ConfigParser ()
    if len (parser.read (SHAREFILE)) == 0:
        sys.exit (1)

    if not parser.has_section (sharename):
        sys.exit (1)

    parser.remove_section (sharename)

    file = open (SHAREFILE, "w")
    parser.write (file)
    file.close ()

f = open ("/home/federico/kk", "w")
for i in range (0, len (sys.argv)):
    f.writelines ('arg "%s"\n' % sys.argv[i])
f.close ()
    
command = sys.argv[2] # argv[1] is "usershare"

if command == "list":
    list_shares ()
elif command == "add":
    add_share (sys.argv[3], sys.argv[4], sys.argv[5], sys.argv[6])
elif command == "delete":
    delete_share (sys.argv[3])
else:
    sys.exit (1)
