#! /bin/sh
#
# smbshared	smbshared daemon
#				Daemon that manage samba shares
#
# Authors:	<sebastien.estienne@gmail.com>
#

. /lib/lsb/init-functions

set -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DESC="Samba sharing daemon"
NAME="smbshared"
DAEMON=/usr/bin/$NAME

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

#
#	Function that starts the daemon/service.
#
d_start() {
    $DAEMON
}

#
#	Function that stops the daemon/service.
#
d_stop() {
    $DAEMON -k || /bin/true
}


case "$1" in
  start)
	log_begin_msg "Starting $DESC: $NAME"
	d_start
	log_end_msg $?
	;;
  stop)
	log_begin_msg "Stopping $DESC: $NAME"
	d_stop
	log_end_msg $?
	;;
  restart|force-reload)
	log_begin_msg "Restarting $DESC: $NAME"
	d_stop
	sleep 1
	d_start
	log_end_msg $?
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
